if (self.CavalryLogger) { CavalryLogger.start_js(["ifHJ9"]); }

__d("AutoFocusableLink.react",["Link.react","ReactDOM"],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(a){babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.componentDidMount=function(){this.props.autoFocus&&b("ReactDOM").findDOMNode(this).focus()};return c}(b("Link.react"));e.exports=a}),null);
__d("getVisibleValueForContentStateWithMessengerEmoji",["EmojiFormat.bs","emptyFunction"],(function(a,b,c,d,e,f){"use strict";__p&&__p();function a(a){__p&&__p();var c=a.getBlockMap().map(function(c){__p&&__p();var d=c.getText(),e="";c.findEntityRanges(b("emptyFunction").thatReturnsTrue,function(f,g){__p&&__p();var h=c.getEntityAt(f);if(!h)e+=d.slice(f,g);else{h=a.getEntity(h);if(h.getType()==="EMOTICON")e+=h.getData().originalEmoticon;else if(h.getType()==="EMOJI"){h=h.getData().type;h=b("EmojiFormat.bs").codeStringToCodeArray(h);e+=String.fromCodePoint.apply(String,h)}else e+=d.slice(f,g)}});return e});return c.join("\n")}e.exports=a}),null);
__d("MercuryTypingAnimation_DEPRECATED.react",["cx","React","joinClasses"],(function(a,b,c,d,e,f,g){"use strict";__p&&__p();a=function(a){babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.render=function(){var a;return(a=b("React")).jsx("div",{className:b("joinClasses")("_4a0v _1x3z",this.props.className),children:a.jsxs("div",{className:"_4b0g",children:[a.jsx("div",{className:"_5pd7"}),a.jsx("div",{className:"_5pd7"}),a.jsx("div",{className:"_5pd7"})]})})};return c}(b("React").PureComponent);e.exports=a}),null);
__d("MessengerMQTTConnectionEvents",[],(function(a,b,c,d,e,f){"use strict";e.exports={DELTA_EVENT:"messenger-mqtt-delta",STREAM_DISCONNECT:"messenger-mqtt-stream-disconnect",STREAM_CONNECTING:"messenger-mqtt-stream-connecting",STREAM_CONNECT:"messenger-mqtt-stream-connect",STATE_CONNECTED:"Connected",STATE_DISCONNECTED:"Disconnected",STATE_CONNECTING:"Connecting",TYP:"messenger-mqtt-typ"}}),null);
__d("MessengerMQTTGating",[],(function(a,b,c,d,e,f){"use strict";var g={_forcedOff:!1,isEnabled:function(){return!g._forcedOff},turnOff:function(){g._forcedOff=!0}};e.exports=g}),null);
__d("DimensionTracking",["Cookie","Event","debounce","getViewportDimensions","isInIframe"],(function(a,b,c,d,e,f){function a(){var a=b("getViewportDimensions")();b("Cookie").set("wd",a.width+"x"+a.height)}b("isInIframe")()||(setTimeout(a,100),b("Event").listen(window,"resize",b("debounce")(a,250)),b("Event").listen(window,"focus",a))}),null);
__d("EventListener",["Event","TimeSlice","emptyFunction","setImmediateAcrossTransitions"],(function(a,b,c,d,e,f){__p&&__p();function g(a,c,d,e){var f=b("TimeSlice").guard(d,"EventListener capture "+c);if(a.addEventListener){a.addEventListener(c,f,e);return{remove:function(){a.removeEventListener(c,f,e)}}}else return{remove:b("emptyFunction")}}a={listen:b("Event").listen,capture:function(a,b,c){return g(a,b,c,!0)},captureWithPassiveFlag:function(a,b,c,d){return g(a,b,c,{passive:d,capture:!0})},registerDefault:function(a,c){var d,e=b("Event").listen(document.documentElement,a,f,b("Event").Priority._BUBBLE);function f(){g(),d=b("Event").listen(document,a,c),b("setImmediateAcrossTransitions")(g)}function g(){d&&d.remove(),d=null}return{remove:function(){g(),e&&e.remove(),e=null}}}};e.exports=a}),null);
__d("VideoPlayerRegistry",["regeneratorRuntime","Promise","EventEmitter"],(function(a,b,c,d,e,f){__p&&__p();var g=new Set(),h=new(b("EventEmitter"))(),i={ADDED:"added",REMOVED:"removed",addListener:function(a,b){return h.addListener(a,b)},once:function(a,b){return h.once(a,b)},has:function(a){return g.has(a)},add:function(a){if(i.has(a))return!1;g.add(a);h.emit(i.ADDED,a);return!0},remove:function(a){if(!i.has(a))return!1;g["delete"](a);h.emit(i.REMOVED,a);return!0},count:function(){return g.size},getList:function(){return Array.from(g)},getByRootNode:function(a){__p&&__p();var c=this,d;return b("regeneratorRuntime").async(function(e){__p&&__p();while(1)switch(e.prev=e.next){case 0:d=null;this.getList().forEach(function(b){b.getByRootNode()===a&&(d=b)});if(d){e.next=6;break}e.next=5;return b("regeneratorRuntime").awrap(new(b("Promise"))(function(b,d){var e=c.addListener(i.ADDED,function(c){c.getRootNode()===a&&(e.remove(),b(c))})}));case 5:d=e.sent;case 6:return e.abrupt("return",d);case 7:case"end":return e.stop()}},null,this)}};e.exports=i}),null);